export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const CREATING_GAME = 'CREATING_GAME';
export const GAME_STARTED = 'GAME_STARTED';
